- app/controllers/questionnaires_controller.rb
- app/controllers/user_controller.rb
- app/mailers/notify_mailer.rb
- app/models/user.rb
- app/views/user/edit.html.haml
- app/views/user/show.html.haml
- config/routes.rb
- spec/requests/authentication_spec.rb
- spec/requests/questionnaires_spec.rb
- spec/requests/user_spec.rb
Adds a controller to allow user to see their details and change them. The new pages are available at `/user`
Also
- update authentication spec to test confirmation options
- fixed notify issue where template requires `user.name` but method doesn't exist
- ensure users accessing questionnaires are logged in
> ER-1 Allow user to modify their profile

- app/controllers/questionnaires_controller.rb
- app/helpers/application_helper.rb
- app/models/module_item.rb
- app/models/questionnaire.rb
- app/views/content_pages/module_intro.html.haml
- app/views/content_pages/sub_module_intro.html.haml
- app/views/content_pages/text_page.html.haml
- app/views/questionnaires/show.html.haml
- spec/helpers/application_helper_spec.rb
- spec/models/module_item_spec.rb
- spec/models/questionnaire_spec.rb
Adds a "Previous" page link to training module pages
If the page is the first page within a training module, the link is back to the training module index.
> ER-57 Add link to previous page within training module pages

- Dockerfile
- Gemfile
- Gemfile.lock
- adr/0005-content-storage-strategy.md
- app/helpers/content_helper.rb
- app/views/layouts/application.html.haml
Snyk has identified a vulnerability in Govspeak version 3, however the patched version 6 is not yet compatible with Rails 7.
> Drop Govspeak which is not yet secure for use with Rails 7

- app/models/concerns/translate_from_locale.rb
- app/models/content_page.rb
- app/models/module_item.rb
- app/models/youtube_page.rb
- app/views/content_pages/youtube_page.html.slim
- config/locales/modules/one.yml
- config/locales/modules/supporting-physical-development-in-the-early-years.yml
- config/locales/modules/test.yml
- data/modules/supporting-physical-development-in-the-early-years.yml
- data/modules/test.yml
- spec/models/content_page_spec.rb
- spec/models/module_item_spec.rb
- spec/models/youtube_page_spec.rb
Allows a page type to be specified that includes a Youtube video.
Also separates the "test" and "one" content data into separate files.
With this in place the page at `modules/supporting-physical-development-in-the-early-years/content_pages/2` render as shown below:
> Add Model for Youtube pages with matching template

- app/controllers/static_controller.rb
- app/views/static/terms_and_conditions.html.slim
- config/locales/static/terms_and_conditions.yml
- config/routes.rb
- spec/requests/static_spec.rb
Adds a static terms and conditions page
The page renders at `/static/terms_and_conditions` as shown below
> ER 121 - Add a static controller with a sample page

- app/controllers/errors_controller.rb
- app/models/user.rb
- app/views/errors/timeout.html.slim
- config/application.rb
- config/initializers/devise.rb
- config/routes.rb
- spec/controllers/training_modules_controller_spec.rb
- spec/requests/errors_spec.rb
- spec/support/devise.rb
Redirect user to timeout page after 30 minutes of inactivity
[Jira Ticket](https://dfedigital.atlassian.net/browse/ER-141)
With this change in place, if a user tries to access a page after the timeout, they are redirected to this page (please note that I reduced the timeout to 1 minute to test - hence the short time shown on the message):
Note that as warden stores the last request time in session, to test the behaviour session needs to be manipulated. The easiest way to do that is within a controller spec. Therefore, a controller spec was used to test the behaviour rather than a request spec.
> ER-141 Inactivity logged out page

- app/helpers/application_helper.rb
- app/views/questionnaires/show.html.slim
[Jira ER-160](https://dfedigital.atlassian.net/browse/ER-160)
Restyle these two so that:
- A solid boarder appears above the two buttons
- The two buttons are positioned at the same height on the page with the previous link to the left, and next/submit button on the right
- The previous link is restyled as a [GOV.UK](http://gov.uk/) Secondary button
- The next/submit button is restyles as a [GOV.UK](http://gov.uk/) button and the text changed to “Next”
In a desktop browser
In a narrow browser window
> ER-160 Restyle buttons in questionnaire forms to "Previous" and “Next” buttons

- app/controllers/questionnaires_controller.rb
- app/models/user.rb
- app/models/user_answer.rb
- db/migrate/20220414093951_create_user_answers.rb
- db/schema.rb
- spec/factories/user_answers.rb
- spec/models/user_answer_spec.rb
- spec/requests/questionnaires_spec.rb
[Jira ER-157](https://dfedigital.atlassian.net/browse/ER-157)
Add a model to record user answers and update questionnaire controller to populate it.
Each question in a questionnaire will have an active (not archived) `UserAnswer` for the user who submits it. Previous user answers are archived (rather than updated or deleted) as there is a requirement to assess the number of attempts a user makes to get the correct answer.
The assessment is made as to whether an answer is correct as each is stored. This allows the number of correct answers to be determined via:
```ruby
UserAnswer.not_archived.where(user: user, questionnaire: questionnaire, correct: true).count
```
And this can be compared with `UserAnswer.not_archived.where(user: user, questionnaire: questionnaire).count` to determine the …
> ER-157 Store users answers for each questionnaire

- app/models/module_item.rb
- spec/factories/module_items.rb
- spec/models/module_item_spec.rb
Some methods have been added to `ModuleItem` to make it easier to determent where in a training module and/or topic a particular page is. As each page in a training module has a unique module item, these methods will make it easier to track and report on progress through a training module.
This PR also adds a factory for module items
The methods added are:
- `.where_topic` which takes a training module name and topic number and returns all the matching module items in the order they are defined within the YAML files
- `#topic` returns the topic number if the module item name is of the form `1-2-1`, `1.2.1` or `1-2-2-4`, where that number is the third digit group in the sequence (or last digit if just three numbers e.g. 2 from `1-1-2`)
- `#position_within_topic` returns the module item's …
> Adds methods to determine the position of a module item

- app/controllers/questionnaires_controller.rb
- app/models/module_item.rb
- app/models/questionnaire.rb
- app/models/questionnaire_data.rb
- app/models/user_answer.rb
- app/views/questionnaires/show.html.slim
- data/questionnaires/one.yml
- spec/factories/user_answers.rb
- spec/models/questionnaire_data_spec.rb
- spec/models/questionnaire_spec.rb
- spec/models/user_answer_spec.rb
- spec/requests/questionnaires_spec.rb
[Jira ER_156](https://dfedigital.atlassian.net/browse/ER-156)
The questionnaire data can now take a field `require_percentage_correct` which sets the threshold which must be exceeded for a questionnaire submission to be valid. The questionnaire validation has been updated so that:
- if threshold is set and the percentage of correct answers is below the threshold, that the questionnaire is invalid
- if threshold is set and the percentage of correct answers equals or is above the threshold, that the questionnaire is valid
- if no threshold is set and correct answers are set, it is assumed that all questions must be answered correctly for the questionnaire to be valid
- if no threshold is set and no correct answers are set, it is assumed no question matching is needed (questionnaire always …
> ER-156: Add required percentage correct threshold to questionnaire data

- app/controllers/application_controller.rb
- app/controllers/content_pages_controller.rb
- app/controllers/formative_assessments_controller.rb
- app/helpers/application_helper.rb
- app/views/formative_assessments/_assessment_banner.html.slim
- app/views/formative_assessments/show.html.slim
- config/routes.rb
- data/modules/test.yml
- data/questionnaires/one.yml
- data/questionnaires/test.yml
- spec/requests/content_pages_spec.rb
- spec/requests/formative_assessments_spec.rb
- spec/requests/questionnaires_spec.rb
Allows formative assessment to be handled differently to other questionnaires
[JIRA ER-153](https://dfedigital.atlassian.net/browse/ER-153)
A questionnaire can be defined as a formative assessment by setting it's type as `:formative_assessment` in `data/modules/<module_name>.yml`. The questionnaire will then be handled by the formative assessments controller. This has the following behaviour:
- If a user visits a formative assessment and they have no stored answers - they will be presented with a blank form
- If a user visits a  formative assessment and they have stored answers - the form will include the matching result box
- When a user arrives on a blank form page and they enter data, clicking Next will submit the form and display the results.
- Users will not be able to re-submit …
> Add formative assessment controller

- Procfile.dev
- README.md
- bin/docker-dev-restart
- docker-entrypoint.sh
Bootstrapping assets was not working as intended for content designers and an easy way to restart the server was needed. 
- remove unnecessary asset compilation from entrypoint which failed because the preceding yarn process forked
- add convenience script to restart the dev server in docker
- update README
> Simplify asset pipeline bootstrapping in dev

- .github/labeler.yml
This will prevent the `labeler` action from removing `deployed` from open PRs.
Demonstrated below in the conversation.
> Comment out "labeler" match rule for "deployed"

- spec/system/forgotten_password_spec.rb
Fix broken specs. These were caused by introducing specs old URLs (underscores) rather than new URLs (hyphens)
Have used rails URLs rather than explicit to prevent this happening again
> ER-276 update specs to reflect hyphens rather than underscores

- app/controllers/confirmations_controller.rb
- app/views/devise/confirmations/new.html.slim
- app/views/user/check_email_confirmation.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/system/registration_journey_spec.rb
Ticket: [ER-181](https://dfedigital.atlassian.net/browse/ER-181)
- Update 'Check your email' page to work if it cannot access the user's email address
- Change content to reflect this
- This is the case when a user does the following: 
Registration page > Check your email page > Resend your confirmation page > Check your email page
- Add back buttons x 2 to 'Resend your confirmation' page
- Add specs to test acceptance criteria in the ticket
> Er 181 not received confirmation email

- app/views/devise/registrations/edit.html.slim
- app/views/devise/registrations/new.html.slim
- config/locales/en.yml
- spec/system/forgotten_password_spec.rb
- spec/system/registered_user/changing_password_spec.rb
- spec/system/sign_up_spec.rb
Content changes for `Create an early year training account `page
- Added back link to the top of the page
- Updated hint text for email field
- Update field name for password confirmation field
- update email validation message
- update validation message for passwords not matching
- added terms & conditions and privacy policy to page
> create account journey content changes

- config/locales/static/accessibility_statement.yml
- config/locales/static/privacy_policy.yml
- config/locales/static/terms_and_conditions.yml
Links on static pages have incorrect styling:
This PR fixes that on the:
- Accessibility statement page
- Privacy policy page
- Terms and conditions page
> add links with correct styling

- app/controllers/confirmations_controller.rb
- app/mailers/notify_mailer.rb
- app/models/user.rb
- app/views/user/check_email_confirmation.html.slim
- config/locales/devise.en.yml
- config/locales/en.yml
- config/locales/modules/brain-development-and-how-children-learn.yml
- spec/mailers/notify_mailer_spec.rb
- spec/system/registration_journey_spec.rb
This PR for [ER-282](https://dfedigital.atlassian.net/browse/ER-282) and [ER-273](https://dfedigital.atlassian.net/browse/ER-273) introduces a new template for account activation.  Previously the 'confirmation_instructions` template was used both for user account creation and user account update.  Now the template 'activation_instructions' is used for the creation and 'email_confirmation_instructions' is used for the update.  Once this is merged we can remove the 'confirmation_instructions' template on Notify (https://notifications.service.gov.uk)
> Introduce the 'activation_instructions' email

- app/views/content_pages/interruption_page.html.slim
- app/views/layouts/_footer.html.slim
- fix interrupt page on mobile devices
- add space between footer links so they can be clicked on mobile devices
Screenshot (mobile):
> Fix interrupt page on mobile

- app/assets/stylesheets/application.scss
- app/views/formative_assessments/_assessment_banner.html.slim
[ER-311](https://dfedigital.atlassian.net/browse/ER-311)
The assessment banner uses the govuk notification banner component for
both correct and incorrect answers.  Updated to have a red outline and
red background on the title.
If error message componet is preferred, we can update for that, but for
consistency I recommend with staying with the notification banner as
modified.
> ER-311 all error messages to appear red error box

- app/views/training_modules/index.html.slim
[ER-325](https://dfedigital.atlassian.net/browse/ER-325)
The certificate and the course overview page use the same
bullet list of course criteria - match the grammer of the
list.
> Update lead line for course criteria

- app/helpers/content_helper.rb
- app/models/question.rb
- app/views/confidence_checks/show.html.slim
- app/views/formative_assessments/show.html.slim
- app/views/questionnaires/show.html.slim
- app/views/shared/_question_check_boxes.html.slim
- app/views/shared/_question_radio_buttons.html.slim
- app/views/summative_assessments/show.html.slim
- data/questionnaires/alpha.yml
- data/questionnaires/brain-development-and-how-children-learn.yml
Using markdown you can now have the following:
- bullet points in a question
- line breaks in a questions
You can also now replace the `label` attribute (which is used for the **legend** of the question) with a `body` attribute, with no specific styling beyond what is available in markdown.
[ER-307](https://dfedigital.atlassian.net/browse/ER-307)
[ER-308](https://dfedigital.atlassian.net/browse/ER-308)
[ER-326](https://dfedigital.atlassian.net/browse/ER-326)
> ER-307 ER-308 and ER-326 Adds markdown for questions

- app/views/layouts/application.html.slim
Disabled cache for now. need a better solution for third party library with turbo as its difficult to destroy gov uk frontend library and then re-initialise javascript events.
> Full reload for turbo in rails to support third party library

- app/views/layouts/application.html.slim
Reverts DFE-Digital/early-years-foundation-recovery#215
Error messages for forms (handled by turbo) were not being shown.  Reverting to allow error messages.
> Revert "Full reload for turbo in rails to support third party library"

- app/models/content_page.rb
- app/models/training_module.rb
- app/views/content_pages/interruption_page.html.slim
- config/locales/en.yml
[ER-232](https://dfedigital.atlassian.net/browse/ER-323)
Make the formative/summative sections of the interruption page independent.
~~I'm leaving the "Get a certificate of achievement" section in for now - it's in the story but not in the google doc provided by Laura (https://docs.google.com/document/d/1_DDH2mNEyegGHCp_Xy2bQBYDe_Khj2nNKpN2Fjfoxtw/edit?usp=sharing) - the actual text can be managed by the content team if the logic is now correct.~~
Laura has requested it be removed.
> ER-323 Fix interruption page

- config/locales/devise.en.yml
[ER-289](https://dfedigital.atlassian.net/browse/ER-289)
Update the error message show when an already confirmed email address is confirmed again.
> ER-289 Update error message for confirmation already confirmed

- lib/fill_page_views.rb
- lib/tasks/post.rake
- spec/lib/fill_page_views_spec.rb
- terraform/workspace-variables/development.tfvars
- terraform/workspace-variables/staging.tfvars
Release candidate 0.0.25 exceeded timeout due to volume of users (120) and events (16812).
Either an excessive timeout value fourfold greater, or concurrent batches, would be needed for this to be viable at scale.
In the meantime we will run the task on demand.
> Revert to using a manual task run on deployment

- app/views/user/edit_email.html.slim
- app/views/user/edit_name.html.slim
- app/views/user/edit_ofsted_number.html.slim
- app/views/user/edit_password.html.slim
- app/views/user/edit_postcode.html.slim
- app/views/user/edit_setting_type.html.slim
Ticket: [ER-469](https://dfedigital.atlassian.net/browse/ER-469)
- change class to govuk_link_to so it is styled correctly
Screenshots:
Visited link:
Hover link:
> ER-469 cancel buttons on my account page not styled correctly

- .github/workflows/ci-docker-compose.yml
- .github/workflows/ci.yml
- .github/workflows/content.yml
- .github/workflows/development.yml
- .github/workflows/pa11y.yml
- .github/workflows/production.yml
- .github/workflows/qa-docker-compose.yml
- .github/workflows/qa.yml
- .github/workflows/staging.yml
- .github/workflows/teardown.yml
- .github/workflows/trivy.yml
- Gemfile.lock
- fix dependabot PRs struggling by not seeing the blank value for Notify's API key when prepping the DB
- update the workflow action versions still causing deprecation warnings
- bulk update some gems to observe dependabot's reaction
> Bump gem versions

- app/views/notes/_form.html.slim
Ticket: [ER-524](https://dfedigital.atlassian.net/browse/ER-514)
- add space
Screenshot:
> ER-514 add missing space in learning log

- terraform/workspace-variables/production.tfvars
Run `cf update-service ey-recovery-db -p medium-ha-13` before next production deployment to ensure scaling succeeds.
Altering the size of the DB service in Terraform fails to deploy because it also attempts to modify the included extensions.
https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/3488314182/jobs/5836980476
```
~ resource "cloudfoundry_service_instance" "postgres_instance" {
id                             = "99d5eb3d-538a-4788-ae17-cd5a11590db1"
name                           = "ey-recovery-pr-383-db"
~ service_plan                   = "397eff33-450a-4a62-9a67-2124255c92e6" -> "4a2761dd-7c9e-4528-b234-423c848cab77"
tags                           = []
}
Plan: 0 to add, 2 to change, 0 to destroy. …
```
> Deploy after manual update to db service

- terraform/app/modules/paas/inputs.tf
- terraform/app/modules/paas/main.tf
Deployments blocked by bumped version strategy
https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/3523578334/jobs/5908084184#step:8:329
Opting to retain the explicit version number in Terraform
> Update to v3 of the blue-green strategy

- app/controllers/assessment_results_controller.rb
- app/controllers/questionnaires_controller.rb
- app/helpers/content_helper.rb
- app/views/layouts/application.html.slim
- spec/system/assessment_results_spec.rb
- spec/system/content_page_spec.rb
- spec/system/formative_questionnaire_spec.rb
- spec/system/summative_questionnaire_spec.rb
Ticket: [ER-538](https://dfedigital.atlassian.net/browse/ER-538)
- Add back button to each content page
Screenshot:
> ER-538 Add back buttons to training pages

- app/controllers/application_controller.rb
- app/controllers/close_accounts_controller.rb
- app/mailers/notify_mailer.rb
- app/models/user.rb
- app/views/close_accounts/new.html.slim
- config/application.rb
- spec/mailers/notify_mailer_spec.rb
- update wording
- replace bcc in email with separate internal email listing accounts that have been deleted
> Account deletion hotfix

- app/decorators/module_progress_bar_decorator.rb
- config/sitemap.rb
When `sitemap:refresh:no_ping` is run (part of the `paas_web_app_start_command` for development apps) it was failing due to the pages that had been removed. 
Fix for https://early-years-foundation-reform.sentry.io/issues/3920070448
From this workflow: https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/4105734668
[ER-610](https://dfedigital.atlassian.net/browse/ER-610)
[ER-610]: https://dfedigital.atlassian.net/browse/ER-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove deleted pages from sitemap

- config/puma.rb
- docker-compose.yml
- docker-entrypoint.sh
- terraform/app/variables.tf
- terraform/workspace-variables/app_config.yml
- terraform/workspace-variables/content.tfvars
- terraform/workspace-variables/development.tfvars
- terraform/workspace-variables/production.tfvars
- Uses multiple puma workers in production
- Reports to Sentry at boot time (errors and exceptions have not yet been observed)
- Runs asset recompilation in production prior to boot to ensure `application.*` assets are present
> Fix alerts on asset pipeline

- terraform/workspace-variables/app_config.yml
Enables CMS preview testing using integration environment in place of production
Requires a release candidate deployed to staging in order to start testing.
> Mimic CMS workflow using dev/staging

- app/controllers/contentful/base_controller.rb
- app/models/training/content.rb
- app/models/training/module.rb
- config/application.rb
- config/initializers/contentful_rails.rb
- docker-compose.test.yml
- terraform/workspace-variables/app_config.yml
- enable CMS by default (still disabled on production)
- point to the `staging` alias by default (which is currently populated with the `production` environment content)
- disable additional caching except for test runs (slower page loads in production until webhooks are implemented)
> CMS testing on staging

- config/locales/modules/child-development-and-the-eyfs.yml
"chilcare" corrected to "childcare" in: "Some children may have had restricted access or opportunity for physical activity and outdoor space. This may have resulted in reduced movement. Children who have been able to take extended naps and periods of rest may now lack the stamina needed to complete a day in a childcare setting."
> Fixed typo on 1-1-2-6

- .github/workflows/cms.yml
- app/helpers/content_helper.rb
- config/application.rb
- config/puma.rb
- terraform/workspace-variables/app_config.yml
- review app using staging preview
- CMS content triage using GH workflow
- new noisy Devise flash error debugging
- no forced restart for low-level puma errors
- temporarily enable debugging if CMS feature is enabled (all deployments not just review apps)
> Fixes and tests

- .github/workflows/qa.yml
- README.md
- app/controllers/training/modules_controller.rb
- app/models/training/content.rb
- app/models/training/module.rb
- app/services/contentful_data_integrity.rb
- app/views/training/questions/show.html.slim
- spec/cms/services/contentful_data_integrity_spec.rb
- add protocol back to the QA workflow
- add a QA badge to the README
- improve docs for content creation workflow
- defend against unpublished entries when debugging
- satisfy accessibility ensuring forms always have a submit button, disabled where appropriate
Run `./bin/docker-pa11y https://ey-recovery-pr-625.london.cloudapps.digital` where the bot user has already answered https://ey-recovery-pr-625.london.cloudapps.digital/modules/child-development-and-the-eyfs/questionnaires/1-1-1-1b
> ER-668: Snags

- app/views/training/modules/index.html.slim
- app/views/training_modules/index.html.slim
- data/demo-modules.yml
- data/training-modules.yml
- spec/services/course_progress_spec.rb
- spec/system/my_learning_spec.rb
- terraform/workspace-variables/app_config.yml
https://dfedigital.atlassian.net/browse/ER-665
In order for this to merge the CMS demo content in `test` requires the `depends_on` field entries be removed.
Whilst this remains unmerged the CI pipeline will fail for other PRs.
> ER-665 Non-linear flow

- config/initializers/devise.rb
The default for Devise ~4.9 is to use :html and :turbo_stream but we were overriding it with just :html.  I've updated to use the default.
[ER-647](https://dfedigital.atlassian.net/browse/ER-647)
[ER-648](https://dfedigital.atlassian.net/browse/ER-648)
[ER-647]: https://dfedigital.atlassian.net/browse/ER-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ER-648]: https://dfedigital.atlassian.net/browse/ER-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert to Devise default, which uses :html and :turbo_stream

- .github/workflows/azure-deploy-dev.yml
- .github/workflows/tf-azure-deploy-dev.yml
- terraform-azure/local.tf
- terraform-azure/main.tf
This change is necessary as the Azure GitHub Action for ACI doesn't support Private containers for deploying
> ER-698: Script to deploy background worker

- .github/workflows/azure-deploy-dev.yml
- .github/workflows/azure-deploy-review-teardown.yml
- .github/workflows/azure-deploy-review.yml
- .github/workflows/azure-deploy-stage.yml
- .github/workflows/tf-azure-deploy.yml
- terraform-azure/terraform-azure-review/main.tf
- Corrected environment variable name for the container image in the Review Apps workflow
- Reinstated OIDC permission in the Staging workflow
- Removed Sticky settings from Review App Terraform script due to a known bug where the behaviour to clone app configuration is different in the CLI to to that in Portal (ref. https://github.com/Azure/azure-cli/issues/6638)
> ER-697: Patch Review Apps and Staging workflow

- app/models/data/user_overview.rb
- config/initializers/que.rb
- spec/models/data/user_overview_spec.rb
Comment out continue training mail job. Job is slow running and is being removed until we have a more performant alternative
> Remove continue training mail job

- app/views/user/show.html.slim
Correct email preferences text on account page to use `my_account.training_emails_true` and `my_account.training_emails_true`
> fix email preference text on account page

- app/assets/stylesheets/quote.scss
- app/views/govspeak/_quote.html.slim
- config/initializers/govspeak.rb
- spec/helpers/content_helper_spec.rb
[ER-443]
https://app.contentful.com/spaces/dvmeh832nmjc/environments/master/entries/2o8yybdQwLV20OTXYux48c
https://ey-recovery-staging.london.cloudapps.digital/modules/module-6/content-pages/6-1-1-1
http://localhost:3000/modules/alpha-clone/content-pages/1-1 (preview only)
```
$QUOTE
this is the quote
this is the citation
$QUOTE
```
[ER-443]: https://dfedigital.atlassian.net/browse/ER-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Big quote markup using bespoke Govspeak tag

- app/models/user.rb
- spec/jobs/continue_training_mail_job_spec.rb
- spec/models/data/user_overview_spec.rb
Update `continue_training_mail_job_recipients` scope so that it is more discerning and selects only users who last visited 4 weeks ago
> additional fix for continue training nudge mail scope

- app/assets/stylesheets/prompt.scss
- app/assets/stylesheets/quote.scss
- app/assets/stylesheets/section-intro.scss
- app/views/markup/_two_thirds.html.slim
- app/views/notes/_form.html.slim
- app/views/training/pages/section_intro.html.slim
- spec/helpers/content_helper_spec.rb
`{two_thirds}` markup tag usage
Quote icon background
> UI adjustments

- app/helpers/link_helper.rb
- config/locales/en.yml
- spec/lib/seed_snippets_spec.rb
[ER-819]
Change `next` and `previous` link labels to improve accessibility
[ER-819]: https://dfedigital.atlassian.net/browse/ER-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change label text for audit and move to locales

- app/views/user/show.html.slim
- config/locales/en.yml
- spec/lib/seed_snippets_spec.rb
[ER-884]
[ER-884]: https://dfedigital.atlassian.net/browse/ER-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change link text instead of adding labels on my account

- .env.example
- .github/workflows/content.yml
- .github/workflows/development.yml
- app/controllers/application_controller.rb
- app/services/content_integrity.rb
- config/application.rb
- spec/system/maintenance_spec.rb
- terraform/workspace-variables/app_config.yml
- https://eyrecovery-review-pr-965.azurewebsites.net
- https://ey-recovery-pr-965.london.cloudapps.digital
> Revise maintenance page feature

- .github/workflows/azure-deploy-review.yml
- app/assets/stylesheets/card.scss
- app/controllers/learning_controller.rb
- app/decorators/module_overview_decorator.rb
- app/services/module_progress.rb
- app/views/learning/_card.html.slim
- app/views/learning/show.html.slim
- config/application.rb
- config/locales/en.yml
- db/seeds/users.yml
- spec/lib/seed_snippets_spec.rb
- spec/system/my_learning_spec.rb
[ER-864]
New resources using a `%{num}` variable:
- `my_learning.progress.percentage`
- `my_learning.progress.viewed`
- `my_learning.progress.remaining`
[ER-864]: https://dfedigital.atlassian.net/browse/ER-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-864 card progress bar

- app/assets/stylesheets/card.scss
[ER-864]
[ER-864]: https://dfedigital.atlassian.net/browse/ER-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-864 Pin progress bar to bottom of card

- app/controllers/application_controller.rb
- app/controllers/registration/terms_and_conditions_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/sessions_controller.rb
- app/forms/registration/terms_and_conditions_form.rb
- app/views/registration/terms_and_conditions/edit.html.slim
- config/application.rb
- config/locales/en.yml
- config/routes.rb
- config/sitemap.rb
- spec/controllers/users/omniauth_callbacks_controller_spec.rb
- spec/lib/seed_snippets_spec.rb
- spec/requests/authentication_spec.rb
- spec/system/confirmed_user/completing_registration_spec.rb
- spec/system/sign_in_spec.rb
[ER-876](https://dfedigital.atlassian.net/browse/ER-876?atlOrigin=eyJpIjoiNjNkMGM2MTQ2MmQyNDU2MTgxYmQ5MTkyMTdmYjFlNDgiLCJwIjoiaiJ9)
Create terms and conditions page for Gov One Login users creating an account. This will be the first step of the registration flow
[ER-876]: https://dfedigital.atlassian.net/browse/ER-876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-876 gov one terms and conditions page

- app/controllers/home_controller.rb
- app/views/layouts/_flash.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/lib/seed_snippets_spec.rb
- spec/system/front_page_spec.rb
[ER-872] 
Add banner regarding the change to Gov One authentication. This changes a resource and adds a new one.
- `banners.important`: Important
- `banners.gov_one`: tbc
[ER-872]: https://dfedigital.atlassian.net/browse/ER-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-872 GovOne Banner

- .env.example
- app/models/page/resource.rb
- lib/seed_snippets.rb
- lib/tasks/cms.rake
- spec/models/page/resource_spec.rb
- spec/models/page_spec.rb
- spec/system/account_page_spec.rb
CMS resources will ideally have parity with I18n locales. Add a rake task to help identify gaps and bolster test coverage.
> Quick CMS resource debugger

- app/models/data_analysis/local_authority_user.rb
- spec/factories/users.rb
- spec/models/data_analysis/local_authority_user_spec.rb
[ER-899](https://dfedigital.atlassian.net/browse/ER-899)
Update to ensure only active users are reported for local authority user
[ER-899]: https://dfedigital.atlassian.net/browse/ER-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-899 Local Authority User active user update

- app/forms/registration/local_authority_form.rb
- data/local-authority.yml
[ER-924](https://dfedigital.atlassian.net.mcas.ms/browse/ER-924)
Wording has been updated for Cumberland and Westmorland and Furness to include information about the previous local authority for these LA's
The wording in the brackets is not included when this is saved
[ER-924]: https://dfedigital.atlassian.net/browse/ER-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-924 Update wording for updated LA list

- app/forms/registration/local_authority_form.rb
- app/models/trainee/authority.rb
- spec/requests/registration/local_authorities_spec.rb
This update is to fix the failing local authority spec following the LA list update (for [ER-924](https://dfedigital.atlassian.net.mcas.ms/browse/ER-924))
[ER-924]: https://dfedigital.atlassian.net/browse/ER-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix failing LA spec following update to LA list

- .rubocop_todo.yml
- app/decorators/next_page_decorator.rb
- app/decorators/pagination_decorator.rb
- app/forms/form_option.rb
- app/helpers/link_helper.rb
- app/models/training/content.rb
- app/models/training/question.rb
- app/services/assessment_progress.rb
- app/services/content_changes.rb
- app/services/module_progress.rb
- app/views/notes/_form.html.slim
- app/views/training/questions/show.html.slim
- config/environments/test.rb
- config/initializers/types.rb
- config/locales/en.yml
- lib/content_seed.rb
- lib/content_test_schema.rb
- lib/migrate_training.rb
- spec/decorators/next_page_decorator_spec.rb
- spec/helpers/link_helper_spec.rb
- spec/lib/seed_snippets_spec.rb
Work on feedback forms is increasing the complexity of navigating through pages and these changes will help improve functionality and testing.
Consolidates next link logic into a single location, introduces better type checks, and adds new CMS resources:
1. `next_page.missing` Next page has not been created
2. `next_page.section` Start section
3. `next_page.next` Next
4. `next_page.start_test` Start test
5. `next_page.save_continue` Save and continue
6. `next_page.finish_test` Finish test
7. `next_page.finish` Finish
> Next link logic

- spec/lib/content_test_schema_spec.rb
- spec/support/ast/alpha-fail-response.yml
- spec/support/ast/alpha-pass-response.yml
- spec/support/shared/with_automated_path.rb
- spec/support/shared/with_events.rb
- spec/support/shared/with_progress.rb
- spec/system/confidence_check_spec.rb
- spec/system/event_log_spec.rb
- spec/system/formative_question_spec.rb
- spec/system/module_overview_progress_spec.rb
- spec/system/summative_assessment_spec.rb
Make it easier to test using YAML (supporting responses after migration) and handle the more nuanced journeys, for example, the new feedback questions.
> Refactor testing abstraction to help spec feedback form responses

- config/application.rb
- spec/config_spec.rb
- spec/requests/timeout_warning_spec.rb
[ER-954]
Update timeout minutes to 60 to match SSO timeout length
[ER-954]: https://dfedigital.atlassian.net/browse/ER-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-954 Timeout post SSO

- app/assets/stylesheets/application.scss
- app/views/training/questions/show.html.slim
[ER-927](https://dfedigital.atlassian.net.mcas.ms/browse/ER-927)
Updated margin-bottom to ensure there is spacing between the Learning Check and the HR. The margin-bottom for this is 20px. This is also applied to all the banners which have the assessment results styling here.
[ER-927]: https://dfedigital.atlassian.net/browse/ER-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ER-927 Learning Check styling update

- config/initializers/grover.rb
We are currently experiencing timeout issues in Grover when a user attempts to view their certificate at the end of a module. This fix attempts to resolve this. This not currently being reported as an issue on the live service, but this behaviour can be seen in lower environments.
This solution has been recommended in the Grover issues discussion.
> Attempt to fix Grover

- app/controllers/users/omniauth_callbacks_controller.rb
- app/services/gov_one_auth_service.rb
Add rescues in the omniauth_callbacks_controller and gov_one_auth_service so that we can have a better quality of error logs to help define the log-in issue
> EYCDTK-120-add-logging-to-omniauthcallback-methods

- app/controllers/users/omniauth_callbacks_controller.rb
As per cacthup with ben, this line is no longer needed due to:  https://github.com/DFE-Digital/early-years-foundation-recovery/pull/1387
> EYCDTK-227-remove-redundant-code-in-omniauthcallbackkcontroller

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/certificate.scss
- app/assets/stylesheets/interruption.scss
- app/assets/stylesheets/prompt.scss
Update for govuk-crest and updating colour to fix deprecation warning. Further information about these warnings can be found here: https://sass-lang.com/documentation/breaking-changes/color-functions/
> EYCDTK-308 Asset and Colour update

- Gemfile.lock
Update Rack to 3.1.10 to address [this issue](https://github.com/DFE-Digital/early-years-foundation-recovery/security/dependabot/123)
> Update Rack to 3.1.10

- Gemfile.lock
This dependency update is to resolve deprecation warnings
> Update factory_bot_rails to latest version

- app/views/notes/_form.html.slim
Update focus to false in notes form so that screenreaders autofocus to the log when doing a module
https://dfedigital.atlassian.net/jira/software/projects/EYCDTK/boards/251?selectedIssue=EYCDTK-396
> Update focus to false in notes _form 

- terraform-azure/terraform-azure-database/main.tf
Add logging for queries over 5 seconds
https://techcommunity.microsoft.com/blog/adforpostgresql/enable-slow-query-logging-in-azure-database-for-postgresql/3639626 https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server_configuration https://github.com/search?q=azurerm_postgresql_flexible_server_configuration+log_min_duration_statement&type=code
Add terraform to set server parameter of log_min_duration_statement to 5 seconds (5000 ms). To disable set to -1.
> BV - Add logging for queries over 5 seconds

- .gitignore
- app/assets/stylesheets/module-overview.scss
- app/views/learning/_completed_modules.html.slim
- app/views/training/modules/_section.html.slim
- app/views/training/modules/_subsection.html.slim
- app/views/training/modules/show.html.slim
- spec/system/module_overview_progress_spec.rb
> EYCDTK-420 Update visual list on modules page

- app/decorators/pagination_decorator.rb
- spec/decorators/feedback_pagination_decorator_spec.rb
- spec/decorators/module_debug_decorator_spec.rb
- spec/decorators/pagination_decorator_spec.rb
- spec/system/certificate_spec.rb
Update section count to ensure that a section is not a feedback page. If it is a feedback page it would therefore be excluded from the list
Before:
After:
> Update section count so that it ignores feedback as a section

- app/services/module_progress.rb
- spec/services/module_progress_spec.rb
Sort the module_progress events by time so that when milestone method uses the .last function we are confident that the last is chronologically correct.
> Update module_progress event so it uses time 

- app/controllers/release_controller.rb
- spec/controllers/release_controller_spec.rb
Remove reference to resetting resource cache key - as it is inaccessible due to its folder structure and is automatically reset as a child of 'page' and therefore redundant.
https://dfedigital.atlassian.net/browse/EYCDTK-566
This should fix the 500 errors we've been seeing in contentful and sentry.
> EYCDTK-556 Contentful publish issue
