DFE-Digital/early-years-foundation-recovery

app/models/concerns/yaml_folder.rb
app/models/questionnaire.rb
app/models/recap_training.rb
app/models/topic.rb
data/questionnaires/simple.yml
spec/models/questionnaire_spec.rb

A Questionnaire is just a named group of questions.
I was thinking of building the data such that each level (questionnaire, question, answer) had it's own model. However, I now think the simpler approach presented here will do the job as well.
With this structure and questionnaire can be retrieve by name:
```ruby
questionnaire = Questionnaire.find_by(name: :simple)
```
The methods, `heading`, and `content` return text (or markup) to be displayed at the page top (or first page/question of questionnaire)
The method `questionnaire.questions` returns the question data for that questionnaire. For this initial simple example, the data looks like this:
```ruby
{:one_from_many=>                              
{:multi_select=>false,                       
:label=>"Select one from many", …
```

Create a basic Questionnaire structure

---

Gemfile
Gemfile.lock

Was able to get a test application up and running with govuk-frontend by adding:
* `cssbundling-rails`
* `jsbundling-rails`

Add css and js bundling rails gems

---

.github/RunPa11y.yml

ER-50 - Create a template Pa11y GitHub Action to execute Pa11y against a given URL

Create template Pa11y action

---

.github/workflows/trivy.yml
adr/0009-trivy.md

Add Trivy to the automated workflows to test Docker for vulnerabilities

Add Trivy workflow

---

app/assets/config/manifest.js
config/locales/modules/supporting-physical-development-in-the-early-years.yml

Updating the path image file extension fixed the problem in production (works in dev without the extension)

Fix image locations in assets

---

.github/workflows/trivy.yml
Dockerfile

Apply vulnerability fixes identified by Trivy

Add explicit versions to Dockerfile

---

app/assets/stylesheets/application.scss
app/controllers/registrations_controller.rb
app/controllers/user_controller.rb
app/views/devise/registrations/new.html.slim
app/views/devise/sessions/new.html.slim
app/views/devise/shared/_form_wrap.html.slim
app/views/layouts/application.html.slim
app/views/user/check_email.html.slim
config/routes.rb
spec/requests/user_spec.rb

[ER-2](https://dfedigital.atlassian.net/browse/ER-2)
Updates registration flow, after entering information the user is redirected to a "check your email" page.

Add "Check your email" page after account setup

---

app/views/errors/timeout.html.slim
config/application.rb

Update following feedback to [Jira Ticket ER-141](https://dfedigital.atlassian.net/browse/ER-141)
Specifically:
- The timeout needs to occur after 15 minutes rather than 30.
- There was a missing full stop at the end of the line starting "You have not done anything ..."

Update timeout to 15 mins and add missing full stop

---

app/views/static/privacy_policy.html.slim
config/locales/static/privacy_policy.yml
spec/requests/static_spec.rb

Privacy Policy page
[ER-137](https://dfedigital.atlassian.net/browse/ER-137)

add privacy policy page and content

---

.env.example
.github/workflows/content.yml
.github/workflows/label.yml
.github/workflows/production.yml
.github/workflows/staging.yml
README.md
config/environments/production.rb
terraform/workspace-variables/app_config.yml

- trigger production on tag release
- add missing app envs to prod/staging
- consolidate some env vars
- document pipeline in the README

Deployment snags

---

data/yaml_file_readme.md

Adds a README describe the use of YAML files withing the project.

Add YAML file README

---

.github/workflows/teardown.yml
config/locales/modules/one.yml

Mindful that the label may have been removed automatically by
subsequent pushes

Attempt to teardown every PR

---

app/controllers/settings_controller.rb
app/views/settings/cookie_policy.html.slim
config/routes.rb
spec/requests/settings_spec.rb

[ER-138](https://dfedigital.atlassian.net/browse/ER-138)
Placeholder page for cookies

Er 138 cookies page

---

.env.example
.github/workflows/content.yml
.github/workflows/teardown.yml
Dockerfile
README.md
config/application.rb
terraform/app/modules/paas/inputs.tf
terraform/app/modules/paas/locals.tf
terraform/app/modules/paas/main.tf
terraform/app/terraform.tf
terraform/app/variables.tf
terraform/workspace-variables/app_config.yml
terraform/workspace-variables/content.tfvars
terraform/workspace-variables/production.tfvars

- remedy the service name collision so multiple feature branches can be deployed.
- extend the timeout to be one hour
- cache Yarn and production Bundler assets for performance

Improve review app deployment

---

app/views/layouts/_footer_content.html.slim
app/views/layouts/application.html.slim

Footer links for static pages
[ER-167](https://dfedigital.atlassian.net/browse/ER-167) (all footer links)
[ER-138](https://dfedigital.atlassian.net/browse/ER-138) (cookies)

Add links to footer

---

app/views/layouts/application.html.slim

[ER-236](https://dfedigital.atlassian.net/browse/ER-236)
Minor bug - this PR fixes the whitespace issue below the footer.

add govuk-template class to html doc

---

config/initializers/devise.rb
config/locales/devise.en.yml
spec/system/all_users_signing_in_spec.rb

- Change max number of incorrect password attempts to 6
- Update wording in locked account message

Er 213 incorrect password 6 attempts

---

app/views/layouts/_footer_content.html.slim
app/views/static/get_help.html.slim
config/locales/static/get_help.yml

[ER-139](https://dfedigital.atlassian.net/browse/ER-139)
Placeholder page for the Contact us/Get help page

Er 139 get help page

---

.env.example

update out of date comment

---

app/views/extra_registrations/_name.html.slim
app/views/extra_registrations/_setting.html.slim
app/views/extra_registrations/edit.html.slim
app/views/user/edit_email.html.slim
app/views/user/edit_name.html.slim
app/views/user/edit_ofsted_number.html.slim
app/views/user/edit_password.html.slim
app/views/user/edit_postcode.html.slim
config/locales/en.yml

Content corrections for [ER-131](https://dfedigital.atlassian.net/browse/ER-131) forms under `/my-account`

Correct form inconsistencies

---

app/views/devise/passwords/new.html.slim
app/views/devise/sessions/new.html.slim

Ticket: https://dfedigital.atlassian.net/browse/ER-216
- reorder code to move details dropdown box above sign in button, as in design
- comment out 'Remember me' button as it isn't doing anything at the moment

ER-216 Reset your password link on sign in page

---

app/controllers/content_pages_controller.rb
app/controllers/formative_assessments_controller.rb
app/helpers/application_helper.rb
app/views/shared/_question_check_boxes.html.slim
app/views/shared/_question_radio_buttons.html.slim
data/questionnaires/brain-development-in-the-early-years.yml

Formative assessment

---

app/views/user/check_email_password_reset.html.slim
config/locales/en.yml
spec/system/all_users_signing_in_spec.rb
spec/system/forgotten_password_spec.rb

- Update text on `check_email_password_reset` page
- Move text to locales file
- Add specs to test functionality on `check_email_password_reset` page
- Move all forgotten password specs to one file
- Renamed forgotten password file

Er 185 check your email for password reset

---

config/locales/modules/brain-development-and-how-children-learn.yml
config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/personal-social-and-emotional-development.yml

Made a number of policy updates to the content for Modules 2 and 3, as well as changing references to 'parents' to 'parents and carers' across modules 1, 2 and 3. 
For further details of which changes I've made see here: 
https://docs.google.com/spreadsheets/d/1fD6es93ggMSCcduppgp10PfyM-SdGNLIYQxpOe11ujg/edit#gid=0

Jennypendriss updates 13june

---

app/views/user/check_email_confirmation.html.slim
config/locales/en.yml

Bug ticket [ER-269](https://dfedigital.atlassian.net/browse/ER-269)
Update text to reflect design

ER-269 Fix check email confirmation text

---

app/models/question.rb
config/initializers/devise.rb
ui/pages/privacy_policy.rb
ui/pages/terms_and_conditions.rb
ui/sections/footer.rb

Turn on email notifications for password change and email changed
Note:
Needed to add a fix for forgotten password spec which was using old style (underscore) urls.

ER-246 and ER-247

---

app/views/layouts/_analytics_body.html.erb
app/views/layouts/_analytics_header.html.erb
app/views/layouts/application.html.slim

Ticket: [ER-267](https://dfedigital.atlassian.net/browse/ER-267)
Add google tag manager code as partials

ER-267 add google tag manager as partials

---

config/locales/modules/brain-development-and-how-children-learn.yml
config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/personal-social-and-emotional-development.yml

I've got a note of where blockquotes need to go back in when the styling is fixed
Added Laura H's MS forms feedback links to the confidence check introduction.

Removed blockquote styling, added feedback links

---

app/controllers/extra_registrations_controller.rb
spec/requests/extra_registrations_spec.rb

[ER-280](https://dfedigital.atlassian.net/browse/ER-280)
Redirect to the `my-learning` page after registration is complete

redirect to my learning page after registration

---

config/locales/modules/brain-development-and-how-children-learn.yml
config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/personal-social-and-emotional-development.yml

Moved the feedback form link to after the confidence check

---

app/views/training_modules/certificate.html.slim
config/locales/modules/brain-development-and-how-children-learn.yml
config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/personal-social-and-emotional-development.yml
config/locales/settings/cookie_policy.yml
data/modules/brain-development-and-how-children-learn.yml
data/modules/child-development-and-the-eyfs.yml
data/modules/personal-social-and-emotional-development.yml
data/questionnaires/brain-development-and-how-children-learn.yml
data/questionnaires/child-development-and-the-eyfs.yml
data/questionnaires/personal-social-and-emotional-development.yml

Mo, please could you check that this isn't going to break anything with the certificate? I only changed text and it looks ok on localhost but thought better to check!

Helen snagging 27jun

---

app/views/devise/sessions/new.html.slim
app/views/layouts/_footer.html.slim
app/views/static/contact.html.slim
app/views/static/other_problems_signing_in.html.slim
app/views/static/privacy_policy.html.slim
app/views/user/check_email_confirmation.html.slim
app/views/user/check_email_password_reset.html.slim
config/locales/static/contact.yml
config/locales/static/other_problems_signing_in.yml
spec/requests/static_spec.rb
spec/system/forgotten_password_spec.rb

ER-272 related
Contact us form links (open in new tab)
Added other problems signing in page

contact us form links & other problems signing in

---

app/controllers/user_controller.rb
app/views/devise/passwords/edit.html.slim
app/views/devise/passwords/new.html.slim
app/views/extra_registrations/_setting.html.slim
config/locales/devise.en.yml
config/locales/en.yml
spec/controllers/user_controller_spec.rb
spec/system/forgotten_password_spec.rb
spec/system/registered_user/changing_password_spec.rb

Additional content changes to:
- Resend your confirmation
- Choose a new password page
- Sign in page
- My learning page
- About your setting page - updates to text and hint text

Additional content changes

---

app/assets/stylesheets/application.scss
app/views/training_modules/show.html.slim

Ticket: [ER-329](https://dfedigital.atlassian.net/browse/ER-329)
Wrap text so progress indicator displays correctly on mobile

ER-329 Module overview page text wrapping

---

app/assets/stylesheets/application.scss
app/views/home/index.html.slim
app/views/learning/_card.html.slim
app/views/learning/show.html.slim

Ticket: [ER-330](https://dfedigital.atlassian.net/browse/ER-330)
- make cards show as half width on my learning page when on tablet view
- add bottom margin for spacing when there are multiple cards
- images fill available space in parent container

ER-330 Responsive images

---

app/views/settings/cookie_policy.html.slim

add back link

---

app/helpers/application_helper.rb

In the training modules topic_name is coming up as int so now we convert it to string to we can check for title. this should fix the broken modules.

Updated application helper

---

.github/workflows/trivy.yml

Ignores additional dependencies used only in test or dev

Trivy to target production only

---

app/helpers/content_helper.rb
app/models/confidence_questionnaire.rb
app/models/questionnaire_data.rb
app/models/summative_questionnaire.rb
app/views/confidence_checks/show.html.slim
app/views/formative_assessments/show.html.slim
app/views/summative_assessments/show.html.slim

[ER-312](https://dfedigital.atlassian.net/browse/ER-312)
Add page numbers and total questions to the questionnaire objects

ER-312 Add page numbers to questionnaires

---

app/models/user.rb

[ER-322](https://dfedigital.atlassian.net/browse/ER-322)

Use updated event type for password changing

---

app/assets/stylesheets/application.scss

Ticket: [ER-220](https://dfedigital.atlassian.net/browse/ER-220)
- Nested bullet points (level 2) styling - unfilled circle
Screenshot of updated style:

ER-220 unfilled circles nested bullet points

---

data/modules/personal-social-and-emotional-development.yml

Ticket: [ER-331](https://dfedigital.atlassian.net/browse/ER-331)
Fixed error with page numbers not displaying on page: `/modules/personal-social-and-emotional-development/content-pages/3-2-3-3/`
Screenshot:

ER-331 page number bug

---

app/views/training_modules/certificate.html.slim

[ER-369](https://dfedigital.atlassian.net/browse/ER-369)
Add my learning page link and call to action button to Certificate page

add my learning links and buttons

---

app/views/notes/_form.html.slim

[ER-393]
[ER-393]: https://dfedigital.atlassian.net/browse/ER-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Styling for learning log text box

---

config/locales/static/whats_new.yml

Ticket: https://dfedigital.atlassian.net/browse/ER-448
Text updates

ER-448 Urgent text changes

---

data/modules/child-development-and-the-eyfs.yml

All the pages need to be unique - certificate page was named the same as the confidence check

Rename certificate page so that it is unique

---

config/locales/modules/personal-social-and-emotional-development.yml

ER-451 module 3 url broken

---

config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/module-4.yml
config/locales/static/terms_and_conditions.yml
data/modules/module-4.yml

Fixes linked to urgently removing video 15 at policy request:
- commented out 4-3-1-2video in the module page list 
- commented out 4-3-1-2video in the module content
Also fixed the date on the terms and conditions

Removed video 15

---

app/views/content_pages/icons_page.html.slim
config/locales/modules/brain-development-and-how-children-learn.yml
config/locales/static/whats_new.yml
data/formative-questionnaires/child-development-and-the-eyfs.yml
data/modules/brain-development-and-how-children-learn.yml
data/modules/child-development-and-the-eyfs.yml
data/summative-questionnaires/personal-social-and-emotional-development.yml

Reordered two questions in module 1
Changed video location in module 2
Corrected link in incorrect answer summary for 9th summative question of module 3 Updated what's new and what to expect pages to include reference to not entering personal or sensitive information in learning log

Urgent amends for private beta mark 2

---

data/video-transcripts/756356870.yml
data/video-transcripts/756703837.yml
data/video-transcripts/756705363.yml

3-2-1-4video
4-3-1-2video2
4-3-1-2video

Three new transcripts

---

config/locales/en.yml
config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/module-4.yml
config/locales/modules/personal-social-and-emotional-development.yml
data/formative-questionnaires/child-development-and-the-eyfs.yml
data/formative-questionnaires/module-4.yml
data/formative-questionnaires/personal-social-and-emotional-development.yml
data/summative-questionnaires/child-development-and-the-eyfs.yml

Non-urgent amends from our review of the private beta mark 2 content

Jenny non urgent pbmk2 amends

---

app/views/layouts/application.html.slim
app/views/training_modules/index.html.slim
app/views/training_modules/show.html.slim

Add content for head to force a reload for the page
[ER-449](https://dfedigital.atlassian.net/browse/ER-449)

[ER-449] Force reload for module overview page to get around dup accordion issue

---

config/locales/en.yml

No link to additional resource until policy approved

added video data usage info to about this training page

---

config/locales/modules/brain-development-and-how-children-learn.yml
config/locales/modules/personal-social-and-emotional-development.yml
data/summative-questionnaires/personal-social-and-emotional-development.yml

Hopefully the final amends re: unwanted and challenging behaviour!

Additional policy amends on unwanted behaviour wording

---

app/controllers/registration/base_controller.rb
app/controllers/registration/local_authorities_controller.rb
app/controllers/registration/names_controller.rb
app/controllers/registration/role_type_others_controller.rb
app/controllers/registration/role_types_controller.rb
app/controllers/registration/setting_types_controller.rb
config/locales/en.yml
config/locales/static/new_registration.yml
data/role-type.yml

Following updates:
[ER-515](https://dfedigital.atlassian.net/browse/ER-515) Success message 
[ER-516](https://dfedigital.atlassian.net/browse/ER-516) End page for update/registration
[ER-517](https://dfedigital.atlassian.net/browse/ER-517) Owner or Director

[ER-515] Minor updates for new registration journey

---

.github/workflows/pa11y.yml
bin/docker-pa11y
config/sitemap.rb
lib/tasks/eyfs.rake

Report failure if the sign-in page is audited multiple times
Example:
https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/3514446405/jobs/5888468626

WCAG audit improvements

---

.yardopts
README.md
RELEASE.md
app/controllers/training_modules_controller.rb
app/views/content_pages/_debug.html.slim
app/views/home/index.html.slim
app/views/layouts/_timeout.html.slim
app/views/layouts/application.html.slim
app/views/questionnaires/_questionnaire_debug.html.slim
app/views/training_modules/_debug.html.slim
app/views/user/_debug.html.slim
bin/cf-stats
config/application.rb
config/environments/production.rb

- use of labels, deployments, release workflow, jira board, DoD & DoR
- task namespaces
- add workflow badges
- QA workflow no longer using docker compose
- add predicates to application to test deployment

Summary of release and agile workflow

---

public/googled75177d9fe6a6e08.html

Ticket: [ER-546](https://dfedigital.atlassian.net/browse/ER-546)
- add site ownership file

ER-546 Set up url on Google Search Console

---

.github/workflows/content.yml
README.md
app/models/training_module.rb
app/views/training_modules/_debug.html.slim
app/views/training_modules/_progress.html.slim
terraform/workspace-variables/app_config.yml

- test tagging deployment in Sentry using PR number
- capture exception and custom message in Sentry
- document error monitoring

Sentry Reporting Audit

---

Gemfile.lock
config/locales/devise.en.yml
spec/system/registered_user/signin_spec.rb
spec/system/sign_in_spec.rb

Ticket: [ER-533](https://dfedigital.atlassian.net/browse/ER-533)
Remove signed in message

ER-533 remove signed in message

---

app/views/errors/internal_server_error.html.slim

https://dfedigital.atlassian.net/browse/ER-547
Update 500 error text for the festive period

ER-547 - Service error page

---

config/initializers/devise.rb
spec/system/sign_in_spec.rb

Ticket: [ER-559](https://dfedigital.atlassian.net/browse/ER-559)

ER-559 lock after 5 unsuccessful login attempts

---

app/assets/stylesheets/application.scss
app/views/assessment_results/show.html.slim
app/views/content_pages/_course_pages_footer.html.slim
app/views/content_pages/certificate.html.slim
app/views/home/index.html.slim
app/views/notes/_form.html.slim
app/views/questionnaires/show.html.slim
app/views/registration/names/edit.html.slim
app/views/training_modules/index.html.slim
app/views/user/edit_email.html.slim
app/views/user/edit_password.html.slim

Tickets: [ER-511](https://dfedigital.atlassian.net/browse/ER-511), [ER-512](https://dfedigital.atlassian.net/browse/ER-512)
- Add buttons to button groups
- Left align buttons where necessary

Er 511, er 512 left align buttons and put in button groups

---

app/controllers/users/sessions_controller.rb
app/helpers/timeout_helper.rb
app/views/layouts/_timeout.html.slim
app/views/layouts/application.html.slim
config/locales/en.yml
spec/system/timeout_modal_spec.rb

Ticket: [ER-537](https://dfedigital.atlassian.net/browse/ER-537)
To do:

Er 537 timeout for non javascript users

---

app/views/errors/internal_server_error.html.slim

Ticket: [ER-551](https://dfedigital.atlassian.net/browse/ER-551)
- Revert temporary xmas message

ER-551 revert error 503

---

data/local-authority.yml

[ER-612](https://dfedigital.atlassian.net/browse/ER-612)
Update of local authority list to the small list of 152 local authorties
[ER-612]: https://dfedigital.atlassian.net/browse/ER-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update local authority list

---

config/locales/modules/personal-social-and-emotional-development.yml

In line with removal of this wording elsewhere on the same page
Please do not merge this until confirmed

Amend to reflection point to remove 'consequences' wording

---

config/locales/modules/child-development-and-the-eyfs.yml
config/locales/modules/personal-social-and-emotional-development.yml
data/formative-questionnaires/personal-social-and-emotional-development.yml

Not to be merged until confirmed please!

Change to consequences wording in reference to behaviour

---

.github/workflows/production.yml
terraform/workspace-variables/development.tfvars
terraform/workspace-variables/production.tfvars
terraform/workspace-variables/staging.tfvars

app instances: production=3, integration/staging=2, review=1 (default)

Change app instance values

---

.github/workflows/production.yml
README.md
policy.json

Some instruction and the `policy.json` needed for initiating autoscaling.

Add policy for auto-scaling

---

.github/workflows/production.yml

Install plugin to set autoscale policy

---

terraform/workspace-variables/app_config.yml

Disable CMS feature flag by default in readiness for rc0.5.0 which includes the final YAML content change.

Disable CMS

---

app/controllers/training/modules_controller.rb
app/decorators/contentful_module_overview_decorator.rb
app/decorators/contentful_module_progress_bar_decorator.rb
app/decorators/module_overview_decorator.rb
app/decorators/module_progress_bar_decorator.rb
app/services/module_progress.rb
app/views/shared/_module_overview_subsection.html.slim
app/views/training/modules/_debug.html.slim
app/views/training/modules/_progress.html.slim
app/views/training/modules/index.html.slim
app/views/training/modules/show.html.slim
spec/system/module_overview_progress_spec.rb
spec/system/progress_bar_spec.rb

https://dfedigital.atlassian.net/browse/ER-441
Replaces https://github.com/DFE-Digital/early-years-foundation-recovery/pull/443

ER-441 Consistent module completion once recorded

---

terraform/workspace-variables/app_config.yml

- sign off using staging against YAML
- reduce puma workers to match dev

Toggle CMS off in staging

---

app/jobs/dashboard_job.rb
app/services/dashboard.rb
spec/services/dashboard_spec.rb

Empty temp directory of previously exported files when updating the dashboard

Background worker housekeeping

---

.github/workflows/ci.yml
app/models/user.rb
spec/models/user_spec.rb

Add registration_complete_any and use first registration date, rather than last

Update user to_csv

---

app/controllers/hook_controller.rb
app/services/contentful_data_integrity.rb
spec/cms/requests/webhooks_spec.rb

[ER-628: secure webhooks using secret header](https://dfedigital.atlassian.net/browse/ER-628)
see https://app.contentful.com/spaces/dvmeh832nmjc/settings/webhooks/6WAnYMMBXwZutBNI1RPMU3/activity-log

ER-628 CMS webhook security

---

config/locales/modules/module-5.yml
data/summative-questionnaires/module-5.yml

Fixed links in summative assessment

---

.github/workflows/tf-azure-deploy-dev.yml
.github/workflows/tf-azure-unit-tests.yml
terraform-azure/main.tf
terraform-azure/outputs.tf
terraform-azure/terraform-azure-database/LICENSE
terraform-azure/terraform-azure-database/README.md
terraform-azure/terraform-azure-database/main.tf
terraform-azure/terraform-azure-database/outputs.tf
terraform-azure/terraform-azure-database/variables.tf
terraform-azure/terraform-azure-network/LICENSE
terraform-azure/terraform-azure-network/README.md
terraform-azure/terraform-azure-network/main.tf
terraform-azure/terraform-azure-network/outputs.tf
terraform-azure/terraform-azure-network/variables.tf
terraform-azure/variables.tf

JIRA - https://dfedigital.atlassian.net/jira/software/projects/ER/boards/125?selectedIssue=ER-688

ER-688: Create Azure Database

---

app/models/training/question.rb
data/formative-questionnaires/bravo.yml
spec/cms/models/training/question_spec.rb

https://dfedigital.atlassian.net/browse/ER-750

[ER-750] append 'select one' to radio button legend

---

app/models/data/returning_users.rb
app/models/data/user_module_completion.rb
app/models/data/user_overview.rb
app/models/user.rb
app/services/dashboard.rb
db/schema.rb
spec/models/data/returning_users_spec.rb
spec/models/data/user_module_completion_spec.rb
spec/models/data/user_overview_spec.rb
spec/services/dashboard_spec.rb

Add new metrics for monitoring engagement following the move to a non-linear flow. These new metrics are:
- Number/% of users who have completed 1 module, 2 modules, 3 modules, 4 modules etc
- Number of user who return to the training weekly, monthly, every 2 months, quarterly
- Number of users who still follow the linear sequence.
https://dfedigital.atlassian.net/browse/ER-753?atlOrigin=eyJpIjoiYjEyZWM5MzRhOWYxNGJiYzkyN2ExYzUyZWMwZmE3MDUiLCJwIjoiaiJ9

ER-753 Non linear insights

---

app/views/learning/show.html.slim

[ER-757](https://dfedigital.atlassian.net/browse/ER-757)- update language on my-modules page to mention non-linear flow
[ER-757]: https://dfedigital.atlassian.net/browse/ER-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ER-757] Add language to my-modules page about non-linear flow

---

terraform-azure/main.tf
terraform-azure/terraform-azure-remote-state/main.tf
terraform-azure/terraform-azure-web/main.tf
terraform-azure/terraform-azure-web/variables.tf

JIRA - https://dfedigital.atlassian.net/jira/software/projects/ER/boards/125?selectedIssue=ER-701

ER-701: Azure - Logging

---

.github/workflows/azure-deploy-dev.yml
.github/workflows/tf-azure-deploy-dev.yml
terraform-azure/local.tf
terraform-azure/main.tf
terraform-azure/terraform-azure-app/LICENSE
terraform-azure/terraform-azure-app/README.md
terraform-azure/terraform-azure-app/main.tf
terraform-azure/terraform-azure-app/variables.tf
terraform-azure/terraform-azure-database/variables.tf
terraform-azure/terraform-azure-network/main.tf
terraform-azure/terraform-azure-network/outputs.tf
terraform-azure/terraform-azure-remote-state/main.tf
terraform-azure/terraform-azure-web/main.tf
terraform-azure/terraform-azure-web/variables.tf
terraform-azure/terraform.tf
terraform-azure/variables.tf

JIRA Story: https://dfedigital.atlassian.net/jira/software/projects/ER/boards/125?selectedIssue=ER-698

ER-698: Azure - Deploy Background Worker

---

.github/workflows/azure-deploy-dev.yml

Reverting Docker Image URL to include registry server

Revert Docker Image URL

---

app/models/user.rb

[ER-572] Processing each of theuser records as we enumberate through them.
Concern is for the number of coercion instances being created.  If that's a problem, need to rethink.
[ER-572]: https://dfedigital.atlassian.net/browse/ER-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ER-572] My second attempt at a solution for User.to_csv 

---

.github/workflows/tf-azure-deploy.yml
terraform-azure/terraform-azure-remote-state/README.md
terraform-azure/terraform-azure-remote-state/main.tf
terraform-azure/terraform.tf

Jira Story: https://dfedigital.atlassian.net/jira/software/projects/ER/boards/125?selectedIssue=ER-706

ER-706: Configuration for Azure Test Subscription

---

terraform-azure/main.tf
terraform-azure/terraform-azure-app/main.tf
terraform-azure/terraform-azure-database/main.tf
terraform-azure/terraform-azure-database/variables.tf
terraform-azure/terraform-azure-web/main.tf
terraform-azure/terraform-azure-web/variables.tf
terraform-azure/variables.tf

JIRA Story: https://dfedigital.atlassian.net/jira/software/projects/ER/boards/125?issueParent=58368&selectedIssue=ER-710

ER-710: Azure - Staging Terraform Scripts

---

.github/workflows/azure-deploy-stage.yml
.github/workflows/tf-azure-deploy.yml

Jira Story: https://dfedigital.atlassian.net/jira/software/projects/ER/boards/125?selectedIssue=ER-709

ER-709: Azure Staging - GitHub Actions Workflow

---

.github/workflows/tf-azure-deploy.yml

- Correction to workflow syntax for multiline command

Azure - Terraform workflow syntax

---

app/views/close_accounts/confirm.html.slim
app/views/close_accounts/edit_reason.html.slim
app/views/close_accounts/new.html.slim
app/views/errors/internal_server_error.html.slim
app/views/errors/not_found.html.slim
config/locales/en.yml
config/sitemap.rb

Fixes for accessibility check errors

Fix duplicate ids and empty elements

---

config/locales/en.yml
spec/lib/seed_snippets_spec.rb

[ER-806]
[ER-806]: https://dfedigital.atlassian.net/browse/ER-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Restore content on experts used in /about-training accordion

---

lib/tasks/cms.rake

Successful GH action run
https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/6036649949/job/16379344729

Correct renamed content checking service

---

.github/workflows/tf-azure-deploy.yml
docker-entrypoint.sh
terraform-azure/local.tf
terraform-azure/main.tf
terraform-azure/terraform-azure-web/appgateway.tf
terraform-azure/terraform-azure-web/variables.tf
terraform-azure/terraform-azure-web/webapp.tf
terraform-azure/variables.tf

- Configure Autoscaling rules for App Service
- Enable seed data for the database
- Clean up terraform variables so that these are configurable centrally. Still a WIP - need to merge so that changes can be tested step by step.

ER-790: Azure Refinements

---

.github/workflows/tf-azure-deploy.yml

- Skip Azure Provider registration

ER-790: Skip Provider Registration

---

.github/workflows/tf-azure-deploy.yml
terraform-azure/main.tf

Er 790 azure refinements

---

Gemfile.lock
app/controllers/training/responses_controller.rb
app/models/data/confidence_check_scores.rb
app/models/data/high_fail_questions.rb
app/models/response.rb
app/models/training/answer.rb
app/models/training/question.rb
app/services/dashboard.rb
db/migrate/20230724160222_add_schema_to_responses.rb
db/schema.rb
lib/tasks/data.rake
spec/factories/response.rb
spec/models/data/confidence_check_scores_spec.rb
spec/models/data/high_fail_questions_spec.rb
spec/models/response_spec.rb
spec/models/training/question_spec.rb
spec/services/dashboard_spec.rb

An updated version of the previous user answer migration

Migrate user answers to response

---

terraform-azure/terraform-azure-web/appgateway.tf

ER-858
Remove Azure app gateway restriction for Contentful API content types
"Content-Type => application/vnd.contentful.management.v1+json"

Remove Azure app gateway restriction for Contentful API content types

---

app/models/training/question.rb
spec/models/data/confidence_check_scores_spec.rb
spec/models/response_spec.rb

Updates for rubocop

---

config/application.rb

https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/6642077233/job/18046320493#step:5:8687

Fix production asset compilation within container build

---

.docker-profile
Dockerfile
docker-entrypoint.sh

Address repeated steps in production Azure deployments

Refactor docker entrypoint

---

app/views/user/show.html.slim

[ER-818]
[ER-818]: https://dfedigital.atlassian.net/browse/ER-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use aria labels on change links instead of hiding text on account page

---

Gemfile
Gemfile.lock
app/helpers/content_helper.rb
app/models/user.rb
app/views/user/edit_password.html.slim
config/initializers/devise_security.rb
config/locales/devise.en.yml
config/locales/devise.security_extension.en.yml
config/locales/en.yml
db/seeds/users.yml
lib/tasks/eyfs.rake
spec/controllers/user_controller_spec.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/system/forgotten_password_spec.rb
spec/system/registered_user/changing_password_spec.rb
spec/system/registered_user/closing_account_spec.rb
spec/system/sign_in_spec.rb
ui/pages/sign_in.rb

Contain at least 2 uppercase letters
Contain at least 2 lowercase letters
Contain at least 2 numbers
Contain at least 2 special characters
Also, added `pwned` gem to check against the Pwned Password API 
https://www.twilio.com/blog/better-passwords-in-ruby-applications-pwned-passwords-api-html

Additional password security

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/assets-page.scss
app/assets/stylesheets/dfe-header.scss
app/assets/stylesheets/icons.scss
app/assets/stylesheets/prompt.scss
app/assets/stylesheets/question.scss
app/controllers/home_controller.rb
app/views/home/_debug.html.slim
app/views/home/_hero.html.slim
app/views/home/index.html.slim
app/views/layouts/_footer.html.slim
app/views/training/modules/index.html.slim
config/application.rb
config/locales/en.yml
spec/lib/seed_snippets_spec.rb

[ER-809]
Added new microcopy resource `home.prompt` 
- [Desktop](https://www.figma.com/proto/FGW1NJJwnYRqoZ2DV0l5wW/Training-content?page-id=7531%3A98342&type=design&node-id=7568-99554&viewport=514%2C160%2C0.04&t=FjcUaSoX9Q58zcAl-1&scaling=min-zoom&starting-point-node-id=7568%3A99554)
- [Mobile](https://www.figma.com/proto/FGW1NJJwnYRqoZ2DV0l5wW/Training-content?page-id=7531%3A98342&type=design&node-id=7609-97804&viewport=396%2C84%2C0.09&t=HN06SeEFXf3UQjIu-1&scaling=min-zoom&starting-point-node-id=7609%3A97804&show-proto-sidebar=1)
[ER-809]: https://dfedigital.atlassian.net/browse/ER-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-809 New home page with hero

---

app/views/user/show.html.slim

[ER-884]
[ER-884]: https://dfedigital.atlassian.net/browse/ER-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-884 My account page

---

adr/0016-devise-security-and-pwned-password-gems.md
adr/ADR.md
config/locales/en.yml
db/seeds/users.yml
lib/tasks/eyfs.rake
spec/controllers/user_controller_spec.rb
spec/factories/users.rb
spec/lib/seed_snippets_spec.rb
spec/system/registered_user/changing_password_spec.rb
spec/system/sign_in_spec.rb
ui/pages/sign_in.rb

[ER-870] Password complexity, update ADR
[ER-870]: https://dfedigital.atlassian.net/browse/ER-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADR for password complexity

---

terraform/workspace-variables/app_config.yml

[ER-877]
[ER-877]: https://dfedigital.atlassian.net/browse/ER-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-877 New production GA tag

---

terraform/workspace-variables/app_config.yml

Set `MAINTENANCE` environment variable to `true` in `app_config.yaml` to enable maintenance page

Enable maintenance page

---

.github/workflows/azure-deploy-dev.yml
.github/workflows/azure-deploy-prod.yml
.github/workflows/azure-deploy-stage.yml

- Prevent Staging and Production Container Instances CPU resource from being downgraded from 2 to 1
- Change to output to none to prevent leakage of credentials

ER: Container CPU -> 2

---

app/jobs/new_module_mail_job.rb
app/models/user.rb
lib/tasks/cms.rake
spec/jobs/new_module_mail_job_spec.rb
spec/models/data_analysis/user_overview_spec.rb

[ER-891]
- Update scope to all users
[ER-891]: https://dfedigital.atlassian.net/browse/ER-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-891 New module mailer update

---

.github/labeler.yml

Introduce `changed-files` key
https://github.com/actions/labeler

Update Label action config

---

.github/labeler.yml

Introduce `any-glob-to-any-file` keyword so it matches examples in the Readme here: https://github.com/actions/labeler . The current configuration is not working with the update that was merged in last week

Label action config update

---

.github/workflows/azure-deploy-dev.yml
.github/workflows/azure-deploy-prod.yml
.github/workflows/azure-deploy-stage.yml

WARNING: Unable to prompt for confirmation as no tty available.
Use --yes.
https://github.com/DFE-Digital/early-years-foundation-recovery/actions/runs/7544538230/job/20538099801#step:9:49

Force confirmation when destroying containers

---

app/models/data_analysis/local_authority_user.rb
app/models/user.rb

This is an additional update to ensure private beta users are also counted in this file
[ER-899](https://dfedigital.atlassian.net/browse/ER-899)
[ER-899]: https://dfedigital.atlassian.net/browse/ER-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-899 LA User update to count all users

---

data/local-authority.yml

[ER-924](https://dfedigital.atlassian.net/browse/ER-924)
Update local authority list to include local authority boundary updates
[ER-924]: https://dfedigital.atlassian.net/browse/ER-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-924 LA list update

---

app/controllers/users/omniauth_callbacks_controller.rb
db/schema.rb

Prevent incorrect GOV.UK One Login error redirect if a user is already signed in

Prevent incorrect error redirect

---

app/models/user.rb
spec/models/user_spec.rb

Add GOV.UK one login info to user data export

Update user data export

---

app/controllers/application_controller.rb
config/application.rb
spec/config_spec.rb

Ensure CMS webhooks continue to work even whilst in maintenance mode

Maintenance mode update 

---

Gemfile
Gemfile.lock
app/services/module_progress.rb
docker-compose.test.yml

- Improve module progress service query performance and docs
- Add DB profiling in dev env
- Fix docker-compose timeout test env

Fix DB performance alerts

---

app/controllers/close_accounts_controller.rb
spec/models/page_spec.rb
spec/requests/static_spec.rb
spec/system/page_title_spec.rb
spec/system/registered_user/closing_account_spec.rb

[ER-603] Account deletion error when adding 'other' reason
Adds fallback value in case of no reason given
[ER-603]: https://dfedigital.atlassian.net/browse/ER-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-603 Account deletion error

---

spec/system/account_page_spec.rb

Validate potential firewall rule issue with `Between X and Y years`

ER-953 registration form bug

---

.github/workflows/azure-deploy-stage.yml
app/controllers/notify_controller.rb
app/controllers/release_controller.rb
app/controllers/webhook_controller.rb
config/routes.rb
spec/requests/webhooks_spec.rb

Refactor hook controllers and change Notify header

Notify callback

---

.github/workflows/azure-deploy-dev.yml
app/jobs/test_bulk_mail_job.rb
app/mailers/notify_mailer.rb
app/models/data_analysis/user_overview.rb
app/models/user.rb
spec/models/data_analysis/user_overview_spec.rb
spec/models/user_spec.rb

- draft test mail job with own template
- export overview of mail recipients and recent deliveries
- export delivery status with user records

Mail metrics

---

app/assets/stylesheets/application.scss
app/views/layouts/_flash.html.slim

Update spacing for success notification banner on My account page so it has the correct margin-bottom

Notification banner spacing update

---

.github/workflows/notify-callback.yml

Default to staging and update header and payload

Update Notify callback simulator

---

app/controllers/registration/early_years_emails_controller.rb
app/controllers/registration/early_years_experiences_controller.rb
app/controllers/registration/names_controller.rb
app/controllers/registration/setting_types_controller.rb
app/controllers/registration/terms_and_conditions_controller.rb
app/controllers/registration/training_emails_controller.rb
app/javascript/application.js
app/models/user.rb
spec/models/user_spec.rb

- Fix JS functions
- Prevent closed accounts from logging back in
- All markdown in account flash messages

ER-1218 closing GovOne accounts

---

.github/workflows/pa11y.yml
app/views/layouts/application.html.slim
app/views/layouts/hero.html.slim

Information about skip link can be found here: https://design-system.service.gov.uk/components/skip-link/

Update to ensure govuk_skip_link links to main content

---

app/models/data_analysis/user_overview.rb
app/models/user.rb
spec/models/data_analysis/user_overview_spec.rb
spec/models/user_spec.rb
spec/requests/webhooks_spec.rb

Add mail success/failure running total and redact notify callback on user

ER-1188 extra mail metrics

---

app/views/user/show.html.slim
config/locales/en.yml
spec/lib/seed_snippets_spec.rb
spec/system/registered_user/closing_account_spec.rb

Remove button to start account closure journey

ER-1299 remove close account button

---

app/views/registration/role_types/edit.html.slim
config/locales/en.yml
spec/lib/seed_snippets_spec.rb

[ER-807](https://dfedigital.atlassian.net/browse/ER-807)
[ER-807]: https://dfedigital.atlassian.net/browse/ER-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ER-807 Minor text fix

---

app/components/header_component.rb

This update is to ensure that the correct styling is applied for active class (following DfE Frontend updates that were merged in)

Header component update

---

app/decorators/previous_page_decorator.rb

Refactor previous link logic when skipping back past the entire module feedback section.

Tweak previous link logic when skipping module feedback

---

app/views/learning/show.html.slim

Revert updates made for completed modules, but keep styling

ER-886 Completed modules revert change

---

app/jobs/content_check_job.rb
config/routes.rb
spec/system/errors_spec.rb

ER-1340 Log update

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

add a fallback to set_time_zone so that if a timezone 'TZ' variable is not set it, it will set to default utc time

EYCDTK-Sorry-there-is-a-problem

---

app/controllers/errors_controller.rb
spec/system/errors_spec.rb

Rescue 404 and 500 errors
https://dfedigital.atlassian.net/jira/software/projects/EYCDTK/boards/251?selectedIssue=EYCDTK-63

Rescue 404 and 500 errors

---

app/assets/stylesheets/application.scss

Update CSS for back links so that they are wcag 2.2. compliant.
https://dfedigital.atlassian.net/jira/software/projects/EYCDTK/boards/251?selectedIssue=EYCDTK-51

EYCDTK-51-Enhance back link

---

app/forms/registration/local_authority_form.rb
app/models/trainee/authority.rb
data/local-authority.yml
spec/requests/registration/local_authorities_spec.rb

[EYCDTK-74](https://dfedigital.atlassian.net/browse/EYCDTK-74)
[EYCDTK-74]: https://dfedigital.atlassian.net/browse/EYCDTK-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EYCDTK-74 Local Authority update

---

app/controllers/users/omniauth_callbacks_controller.rb

Add logging line to staging to uncover users

---

app/controllers/users/omniauth_callbacks_controller.rb

Reverts DFE-Digital/early-years-foundation-recovery#1384

Revert "Add logging line to staging to uncover users"

---

app/controllers/users/omniauth_callbacks_controller.rb

This update has been added to ensure the redirect logic works as expected when a user is already logged in

Update to redirect when already logged in

---

app/models/data_analysis/confidence_check_scores_for_manager_or_leader_and_other.rb
app/models/data_analysis/confidence_check_scores_for_manager_or_leader_only.rb
app/models/user.rb
app/services/dashboard.rb
spec/models/data_analysis/confidence_check_scores_for_manager_or_leader_and_other_spec.rb
spec/models/data_analysis/confidence_check_scores_for_manager_or_leader_only_spec.rb

[EYCDTK-121](https://dfedigital.atlassian.net/browse/EYCDTK-121)
[EYCDTK-121]: https://dfedigital.atlassian.net/browse/EYCDTK-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EYCDTK-121 Confidence score for leaders and managers

---

app/models/data_analysis/assessment_for_leaders_and_managers.rb
app/models/user.rb
app/services/dashboard.rb
spec/models/data_analysis/assessment_for_leaders_and_managers_spec.rb

[EYCDTK-122](https://dfedigital.atlassian.net/browse/EYCDTK-122)
[EYCDTK-122]: https://dfedigital.atlassian.net/browse/EYCDTK-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EYCDTK-122 Assessment new export for managers and leaders

---

app/controllers/users/omniauth_callbacks_controller.rb

Reverts DFE-Digital/early-years-foundation-recovery#1392

Revert "EYCDTK-227-remove-redundant-code-in-omniauthcallbackkcontroller"

---

.github/workflows/trivy.yml

Add fallback to trivy to compensate for ratelimiting errors

EYCDTK-116-ratelimiting-error-when-running-trivy-vulnerability-scanner

---

.github/workflows/tf-azure-deploy.yml

This is a required update to ensure `upload-artifact` and `download-artifact` are up-to-date

Update upload-artifact and download-artifact to v4

---

app/views/training/pages/certificate.html.slim

Update to ensure the feedback cta is not included when viewing the certificate

Certificate update

---

README.md

[EYCDTK-233](https://dfedigital.atlassian.net/browse/EYCDTK-233)
[EYCDTK-233]: https://dfedigital.atlassian.net/browse/EYCDTK-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EYCDTK-233 Update Readme

---

Gemfile.lock

Manually update bootsnap to latest version

Manually update bootsnap

---

app/models/note.rb
spec/models/note_spec.rb

Update note mode so logged_at method references updated_at in stead of created_at

Update note model

---

app/decorators/module_overview_decorator.rb

Update sections method so that we use a flatmap instead of index
Also grab first_item as a method to reduce amount of queries of activerecord

Update sections method in module_decorator

---

data/role-type.yml

Commenting out the extra options as they're not needed currently, but would be good to keep them for ease of change when they are approved over next 2/3 weeks

Revert option changes

---

.github/workflows/tf-azure-deploy.yml

https://dfedigital.atlassian.net/browse/EYCDTK-343

EYCDTK-343 Update terraform config

---

.github/workflows/azure-deploy-dev.yml
.github/workflows/azure-deploy-prod.yml
.github/workflows/azure-deploy-review.yml
.github/workflows/azure-deploy-stage.yml

Upgrade only in dev script - staging and prod to follow later

Azure deploy teardown repairs

---

.github/workflows/azure-deploy-review-teardown.yml

https://dfedigital.atlassian.net/browse/EYCDTK-463

EYCDTK-463 Review teardown version update

---

app/models/trainee/role.rb
app/views/registration/role_types/edit.html.slim
data/role-type.yml

Role hint text will default to nil unless specified in the yml, also added it to the slim

Update role model so it accepts an optional hint text

---

app/views/registration/early_years_experiences/edit.html.slim
app/views/registration/local_authorities/edit.html.slim
app/views/registration/role_type_others/edit.html.slim
app/views/registration/role_types/edit.html.slim
app/views/registration/setting_types/edit.html.slim

Corrects the incorrect use of aria in its fieldset

Accessibility Audit - Incorrect use of ARIA

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/module-overview.scss
app/assets/stylesheets/prompt.scss

Prevent scrolling in two dimentions 
BEFORE:
AFTER:

EYCDTK-469 - Reflow

---

app/views/learning/_card.html.slim

Reverts DFE-Digital/early-years-foundation-recovery#1540

Revert "DTK-534 - progress spoken twice"

---

app/assets/stylesheets/prompt.scss

Fixes resize issue when zooming in 
BEFORE:
AFTER:

EYCDTK-470 - Resize Text fix

---

app/controllers/release_controller.rb
spec/controllers/release_controller_spec.rb
spec/requests/webhooks_spec.rb

Update release controller so that it clears cache on hook consumption and logs correctly
Added specs for this purpose

EYCDTK-605 Contentful updates

---

app/services/module_progress.rb
spec/services/module_progress_spec.rb

Reverts DFE-Digital/early-years-foundation-recovery#1555

Revert "Update module_progress event so it uses time "

---

app/services/module_progress.rb
spec/services/module_progress_spec.rb

DTK-554 - adds fallback for resume

---

app/views/markup/_prompt.html.slim
config/initializers/markdown.rb
spec/helpers/content_helper_spec.rb
spec/requests/snippets_spec.rb

Reverts DFE-Digital/early-years-foundation-recovery#1583

Revert "DTK-706 - broken headers"

---

app/components/header_component.html.slim
app/views/home/_hero.html.slim

[EYCDTK-717](https://dfedigital.atlassian.net/browse/EYCDTK-717)
[EYCDTK-717]: https://dfedigital.atlassian.net/browse/EYCDTK-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EYCDTK-717 Certificate update
